name: Tee-worker CI

# this is a modified version of tee-worker/.github/workflows/build_and_test.yml with
# extra triggering control.
#
# the original file (`tee-worker/.github/workflows/build_and_test.yml`) is kept to sync
# upstream changes, therefore we need to manually apply the changes to this file.

# tried symbolic link -- didn't work, see https://stackoverflow.com/a/71704019

on:
  push:
    branches:
      - dev
    paths-ignore:
      - "**/dependabot.yml"
      - "**/README.md"
  pull_request:
    branches:
      - dev
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  LOG_DIR: logs
  BUILD_CONTAINER_NAME: integritee_worker_enclave_test
  UPLOAD_DOWNLOAD_DIR_PREFIX: /tmp

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# to minimise the changes by setting a default working directory
# please note it only applies to the `run` command, not `use` command
defaults:
  run:
    working-directory: tee-worker

jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    env:
      WORKER_IMAGE_TAG: integritee-worker:dev
      CLIENT_IMAGE_TAG: integritee-cli:dev
      COINMARKETCAP_KEY: ${{ secrets.COINMARKETCAP_KEY }}
      TEERACLE_INTERVAL_SECONDS: 4

    strategy:
      fail-fast: false
      matrix:
        include:
          - test: ts-tests
            flavor_id: sidechain
            demo_name: ts-tests

    steps:
      - uses: actions/checkout@v3

      - name: Pull polkadot image
        run: |
          docker pull parity/polkadot:latest
          docker pull litentry/litentry-parachain:latest

      - name: Download cli artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: 4074196520
          name: integritee-cli-client-sidechain-0ab04e0ed0791ce34c55498f6b2626078a6a08f6.tar.gz
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}

      - name: Download worker artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: 4074196520
          name: integritee-worker-sidechain-0ab04e0ed0791ce34c55498f6b2626078a6a08f6.tar.gz
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}

      - name: Load Worker & Client Images
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker image load --input ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/integritee-worker-sidechain-0ab04e0ed0791ce34c55498f6b2626078a6a08f6.tar.gz
          docker image load --input ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/integritee-cli-client-sidechain-0ab04e0ed0791ce34c55498f6b2626078a6a08f6.tar.gz
          docker images --all

      - name: Re-name Image Tags
        run: |
          docker tag integritee-worker-sidechain-0ab04e0ed0791ce34c55498f6b2626078a6a08f6 ${{ env.WORKER_IMAGE_TAG }}
          docker tag integritee-cli-client-sidechain-0ab04e0ed0791ce34c55498f6b2626078a6a08f6 ${{ env.CLIENT_IMAGE_TAG }}
          docker images --all

      - name: Generate parachain artefacts
        run: |
          ./scripts/litentry/generate_parachain_artefacts.sh

      - name: Build litentry parachain docker images
        run: |
          cd docker
          docker-compose -f litentry-parachain.build.yml build

      - name: Integration Test ${{ matrix.test }}-${{ matrix.flavor_id }}
        timeout-minutes: 30
        if: ${{ matrix.test != 'resume-worker' }}
        run: |
          cd docker
          docker-compose -f docker-compose.yml -f ${{ matrix.demo_name }}.yml up --no-build --exit-code-from ${{ matrix.demo_name }} -- ${{ matrix.demo_name }}

      - name: Integration Test ${{ matrix.test }}-${{ matrix.flavor_id }}
        timeout-minutes: 30
        if: ${{ matrix.test == 'resume-worker' }}
        run: |
          cd docker
          docker-compose -f docker-compose.yml -f resume-worker.yml up --no-build --exit-code-from resume-worker --attach resume-worker relaychain-alice relaychain-bob integritee-node resume-worker

      - name: Stop docker containers
        run: |
          cd docker
          docker compose -f docker-compose.yml -f ${{ matrix.demo_name }}.yml stop

      - name: Collect Docker Logs
        continue-on-error: true
        if: always()
        uses: jwalton/gh-docker-logs@v2
        with:
          tail: all
          dest: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/${{ env.LOG_DIR }}

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs-${{ matrix.test }}-${{ matrix.flavor_id }}
          path: ${{ env.UPLOAD_DOWNLOAD_DIR_PREFIX }}/${{ env.LOG_DIR }}
